### ISSUE TITLE
Feature request: support stick root node

### ISSUE THREAD

**Issue by mzwlevi** [yoyurec/logseq-sticky-headers#1]

**Comment by yoyurec** [comment]
@mzwlevi  any details? ))

**Comment by mzwlevi** [comment]
C is a root node
Sometimes I have a lot of children nodes, It will be convenient when I scroll the screen and stick the root node
<img width="286" alt="Screen Shot 2022-10-05 at 17 15 00" src="https://user-images.githubusercontent.com/78029539/194025588-c7ee87fa-6840-4eaa-8075-50a68376c359.png">

**Comment by mzwlevi** [comment]
This will be helpful when somebody uses outlines without headings

**Comment by yoyurec** [comment]
what about 2nd levels? 3rd?
what about if root node have > 1 line? how to detect it? how to show it?
no no no )) sorry
