### ISSUE TITLE
Transparent Headings Background

### ISSUE THREAD

**Issue by candideu** [yoyurec/logseq-sticky-headers#3]
**Info:**
- OS: Windows 10
- Logseq ver: 0.8.8
- Theme ver: 1.4.1
- [ ] ⚠ Do i have issue with DISABLED my `custom.css`? No

**Description and steps:**
 Create a long page with multiple headings. After a while of scrolling, you will notice that you can see through the sticky heading's background and see the text underneath. This makes the heading hard to read as you scroll.

**Expected behavior:**
 Sticky header's background should be opaque.

**Screenshots**
![image](https://user-images.githubusercontent.com/55474996/195178822-d0440e7b-1116-43cf-8ed0-fde8a4bdfb6b.png)

**Comment by yoyurec** [comment]
sticky headers are very tricky and experimental....
do reload helps?

**Comment by candideu** [comment]
I've tried reload, refresh, _and_  reindex

 
![image](https://user-images.githubusercontent.com/55474996/195183438-152f4929-c599-42a4-b07d-486a09dcdac5.png)

**Comment by yoyurec** [comment]
> refresh, and reindex

this not needed )

* which theme are you using?
* are you using `custom.css`?
* are you sure heading is single line?
* can you attach axample of `.md` file?

**Comment by candideu** [comment]
>     * which theme are you using?
Default light theme, all other plugins are turned off.

>     * are you using `custom.css`?
No

>     * are you sure heading is single line?
Yes, as it's illustrated in both screenshots I've attached

>     * can you attach axample of `.md` file?

Gist: https://gist.github.com/candideu/75cd6324d28f9b4c168975cb0972ee6d

Video: 

https://user-images.githubusercontent.com/55474996/195376268-a8123650-1fc0-4d2b-82ef-cd35a97f11b5.mp4

**Comment by yoyurec** [comment]
check latest release, should be fixed

**Comment by candideu** [comment]
Sweet, thanks for the quick fix! Your plugins make using Logseq a joy :)
