### ISSUE TITLE
Plugin prevents scrolling down the page when document mode toggled

### ISSUE THREAD

**Issue by redactedscribe** [yoyurec/logseq-sticky-headers#5]
**Info:**
- OS: Windows 11
- Logseq ver: 0.8.17
- Theme ver: Default Light Theme
- [ ] ⚠ Do i have issue with DISABLED my `custom.css`? I haven't created/edited any `custom.css`.

**Description:**
When attempting to scroll down the page in the rendered document mode (no dots visible to the left of blocks), Logseq struggles to scroll down at all.

**To Reproduce:**
Enable Sticky Headers plugin v1.4.3. Disabling the plugin fixes the issue.

**Expected behavior:**
Unhindered scrolling regardless of the current document mode.

**Comment by yoyurec** [comment]
this plugin some kind of experimental )
not 100% work in complex cases (((

**Comment by yoyurec** [comment]
i've tested and it scrolls. style of headers little broken in doc mode, but scrolls...
have you tried to reload Logseq (`Ctrl + R`)?

**Comment by yoyurec** [comment]
⚠ Experimental! Will work 99% only with AweomeUI + Awesome Styler nstalled! Other thems and Tabs plugin support not garanted!

**Comment by redactedscribe** [comment]
> i've tested and it scrolls. style of headers little broken in doc mode, but scrolls... have you tried to reload Logseq (`Ctrl + R`)?

@yoyurec I have tried with all plugins disabled except for logseq-sticky-headers and it still gets stuck when scrolling.

I think the problem is somehow related to the _width of the document's editing area_. Here is a video (notice that when the right side bar is opened, the document editing area is reduced and the scroll bug temporarily goes away):

https://user-images.githubusercontent.com/25013746/226200081-fe37d9b5-97df-43c2-9e60-76f6eb549adb.mp4

After more testing, it's not clear what the source of the bug is any more. It also happens in editing mode (i.e. not document mode).

**Comment by redactedscribe** [comment]
@yoyurec Any ideas?

**Comment by redactedscribe** [comment]
Please reopen this issue, thanks.
